dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - python tests/tests.py
env:
  - ARGCOMPLETE=0
  - ARGCOMPLETE=1
install:
  - pip install -r requirements.txt
  - "[ \"$ARGCOMPLETE\" -eq 1 ] && pip install argcomplete || :"
matrix:
  include:
    - python: '3.2'
      dist: trusty
      env:
        - ARGCOMPLETE=0
        - ARGCOMPLETE=1
    - python: '3.3'
      dist: trusy
      env:
        - ARGCOMPLETE=0
        - ARGCOMPLETE=1
